version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: crm_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crm_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/crm_db
      - JWT_SECRET=sua_chave_secreta_jwt
      - PORT=3333
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "npm install
      && npx prisma migrate reset --force
      && npx prisma generate
      && npm run seed
      && npm run dev"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crm_frontend
    environment:
      - VITE_API_URL=http://localhost:3333/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
